package org.mytms.customer.dto;

import java.util.List;

import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class CustomerContactDto {
    private String address;

    private String contactName;

    private String email;

    private long id;

    private Boolean isDefault;

    private String mobile;

    private String post;

    private String remark;

    private String tax;

    private String tel;
}