package org.mytms.customer.dto;

import java.util.Date;
import java.util.List;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class CustomerDto {
    private String area;
    private String auditStatus;
    private String auditor;
    private String bizScope;
    private String businessScope;
    private Integer companyType;
    private String creditCd;
    private String customerCode;
    private String customerEnglishName;
    private String customerName;
    private String fax;
    private long id;
    private String imgLicCert;
    private String imgOrgCert;
    private String imgTaxCert;
    private String legal;
    private Date licCertEnd;
    private Boolean licenseCombine;
    private String officeAddress;
    private Date orgCertBegin;
    private String orgCertCd;
    private Date orgCertEnd;
    private String phone;
    private String profile;
    private Double registerCapital;
    private Date registerDate;
    private String registerNo;
    private String remark;
    private Date settlingTime;
    private String taxCertCd;
}