package org.mytms.customer.dto;

import java.util.List;

import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class CustomerGroupDto {
    private String address;

    private String company;

    private String contact;

    private String contactPhone;

    private Float cooperaPeriod;

    private Integer groupType;

    private Long id;

    private Integer industryType;

    private String portfolio;

    private String remark;
}