package org.mytms.customer.dto;

import java.util.List;

import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class CustomerRelationshipDto {
    private String customerCode;

    private String customerName;

    private Long id;

    private Long parentPmCode;

    private String remark;
}