package org.mytms.customer.dto;

import java.util.List;

import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class DriverDto {
    private Integer auditStatus;

    private String auditor;

    private String domicle;

    private String driverName;

    private String driverNo;

    private Integer drivingType;

    private Long id;

    private String imgDriverCard;

    private String imgIdentify;

    private String imgOther;

    private Integer licensePeriodType;

    private String mobile;

    private String permanentLocation;

    private String remark;

    private Boolean sex;
}