package org.mytms.customer.dto;

import java.util.List;

import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class EquipmentDto {
    private Integer auditStatus;

    private String equipmentName;

    private String equipmentNo;

    private Integer equipmentType;

    private Long id;

    private Long manufacturerId;

    private String outNo;

    private String remark;

    private String serialNo;

    private String specModel;
}