package org.mytms.customer.dto;

import java.util.Date;
import java.util.List;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class InsuranceDto {
	private Long id;

	private Date deadline;

	private Integer driverPolicy;

	private Integer passengerPolicy;

	private String policyNo;

	private String policyType;

	private String remark;

	private String supplier;

	private Integer temperturePolicy;

	private Integer thirdPartyPolicy;

	private Integer totalPolicy;
}