package org.mytms.customer.dto;

import java.util.Date;
import java.util.List;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class InsuranceDto {
	private Long id;

	private String insuranceCompany;

	private Date insuranceDeadline;

	private Integer insuranceMaxamount;

	private String insuranceNo;

	private String remark;
}