package org.mytms.customer.dto;

import java.util.List;

import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class LineDto {
    private Integer businessType;

    private String deliveryArea;

    private String departureCode;

    private String departureName;

    private String destinationCode;

    private String destinationName;

    private Long id;
    private String remark;
}