package org.mytms.customer.dto;

import java.util.Date;
import java.util.List;

import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class VehicleDto {

    private Double approedLoad;

    private Integer auditStatus;

    private String auditor;

    private String brandModel;

    private String businessPolicy;

    private String carOwner;

    private String cardNo;

    private String carriageFormat;

    private String company;

    private String engineNo;

    private Integer equipmentNum;

    private Boolean gps;

    private Long gpsManufacturerId;

    private Boolean hasHygroscop;

    private Boolean hasThermostat;

    private String hygroscopeManufacturerId;

    private Long id;

    private String imgCar;

    private String imgCarOperation;

    private String imgDriving;

    private String imgWarrant;

    private Boolean loan;

    private Integer maxTemp;

    private Integer minTemp;

    private String operateNo;

    private Integer ownerType;

    private Date regdate;

    private String remark;

    private Integer serviceLife;

    private String strongPolicy;

    private Long thermostatManufacturerId;

    private Float vehicleLength;

    private Integer vehicleType;

    private String vin;

    private Double weightLoad;

    private List<InsuranceDto> insurances;
}