package org.mytms.customer.dto;

import java.util.List;

import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
public class WarehouseDto {
    private String address;

    private Double area;

    private String areaCode;

    private String areaName;

    private String cityCode;

    private String cityName;

    private String code;

    private Double cubage;

    private String firefight;

    private String gradeLabel;

    private Integer groundType;

    private Integer heightLevel;

    private Long id;

    private String imgFireAccept;

    private String imgOperatePermit;

    private String imgPlan;

    private String imgProperty;

    private String imgRentalAgreement;

    private String imgWarehouse;

    private Float latitude;

    private Float longitude;

    private String matchEquipment;

    private String name;

    private Boolean operate;

    private String provinceCode;

    private String provinceName;

    private String remark;

    private String security;

    private String struct;

    private Integer warehouseType;
}