package org.mytms.customer.domain;

import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="customer_group")
public class CustomerGroup extends OrgAssignedEntity<Long, CustomerGroup> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(length=256)
	private String address;

	@Basic
	@Column(length=60)
	private String company;

	@Basic
	@Column(length=40)
	private String contact;

	@Basic
	@Column(name="CONTACT_PHONE", length=64)
	private String contactPhone;

	@Basic
	@Column(name="COOPERA_PERIOD", columnDefinition="FLOAT")
	private float cooperaPeriod;

	@Basic
	@Column(name="GROUP_TYPE", columnDefinition="INT")
	private int groupType;

	@Basic
	@Column(name="INDUSTRY_TYPE", columnDefinition="INT")
	private int industryType;

	@Basic
	private String portfolio;

	@Basic
	@Column(length=256)
	private String remark;
}