package org.mytms.customer.domain;

import javax.persistence.*;

import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "customer_contact")
public class CustomerContact extends OrgAssignedEntity<Long, CustomerContact> {
    private static final long serialVersionUID = 1L;

    @Basic
    @Column(length = 256)
    private String address;

    @Basic
    @Column(name = "CONTACT_NAME", length = 20)
    private String contactName;

    @Basic
    @Column(length = 128)
    private String email;

    @Basic
    @Column(name = "IS_DEFAULT")
    private Boolean isDefault;

    @Basic
    @Column(length = 20)
    private String mobile;

    @Basic
    @Column(length = 20)
    private String post;

    @Basic
    @Column(length = 256)
    private String remark;

    @Basic
    @Column(length = 20)
    private String tax;

    @Basic
    @Column(length = 20)
    private String tel;
}