package org.mytms.customer.domain;

import java.util.*;
import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="customer")
public class Customer extends OrgAssignedEntity<Long, Customer> {
    private static final long serialVersionUID = 1L;

    @Basic
    @Column(length=256)
    private String area;

    @Basic
    @Column(name="AUDIT_STATUS", length=64)
    private String auditStatus;

    @Basic
    @Column(length=64)
    private String auditor;

    @Basic
    @Column(name="BIZ_SCOPE", length=256)
    private String bizScope;

    @Basic
    @Column(name="BUSINESS_SCOPE", length=256)
    private String businessScope;

    @Basic
    @Column(name="COMPANY_TYPE", columnDefinition="INT")
    private Integer companyType;

    @Basic
    @Column(name="CREDIT_CD", length=60)
    private String creditCd;

    @Basic
    @Column(name="CUSTOMER_CODE", length=20)
    private String customerCode;

    @Basic
    @Column(name="CUSTOMER_ENGLISH_NAME", length=100)
    private String customerEnglishName;

    @Basic
    @Column(name="CUSTOMER_NAME", length=100)
    private String customerName;

    @Basic
    @Column(length=20)
    private String fax;

    @Basic
    @Column(name="IMG_LIC_CERT", length=256)
    private String imgLicCert;

    @Basic
    @Column(name="IMG_ORG_CERT", length=256)
    private String imgOrgCert;

    @Basic
    @Column(name="IMG_TAX_CERT", length=256)
    private String imgTaxCert;

    @Basic
    @Column(length=60)
    private String legal;

    @Basic
    @Column(name="LIC_CERT_END")
    @Temporal(TemporalType.DATE)
    private Date licCertEnd;

    @Basic
    @Column(name="LICENSE_COMBINE")
    private Boolean licenseCombine;

    @Basic
    @Column(name="OFFICE_ADDRESS", length=256)
    private String officeAddress;

    @Basic
    @Column(name="ORG_CERT_BEGIN")
    @Temporal(TemporalType.DATE)
    private Date orgCertBegin;

    @Basic
    @Column(name="ORG_CERT_CD", length=60)
    private String orgCertCd;

    @Basic
    @Column(name="ORG_CERT_END")
    @Temporal(TemporalType.DATE)
    private Date orgCertEnd;

    @Basic
    @Column(length=20)
    private String phone;

    @Basic
    @Column(length=2048)
    private String profile;

    @Basic
    @Column(name="REGISTER_CAPITAL")
    private Double registerCapital;

    @Basic
    @Column(name="REGISTER_DATE")
    @Temporal(TemporalType.DATE)
    private Date registerDate;

    @Basic
    @Column(name="REGISTER_NO", length=60)
    private String registerNo;

    @Basic
    @Column(length=256)
    private String remark;

    @Basic
    @Column(name="SETTLING_TIME")
    @Temporal(TemporalType.DATE)
    private Date settlingTime;

    @Basic
    @Column(name="TAX_CERT_CD", length=60)
    private String taxCertCd;
}