package org.mytms.customer.domain;

import java.util.*;
import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="customer")
public class Customer extends OrgAssignedEntity<Long, Customer> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(length=40)
	private String abbrev;

	@Basic
	@Column(name="AREA_CODE", length=64)
	private String areaCode;

	@Basic
	@Column(name="AREA_NAME", length=64)
	private String areaName;

	@Basic
	@Column(name="AUDIT_STATUS", columnDefinition="INT")
	private int auditStatus;

	@Basic
	@Column(length=64)
	private String auditor;

	@Basic
	@Column(name="BANK_ACCOUNT", length=64)
	private String bankAccount;

	@Basic
	@Column(name="BANK_ACCOUNT_NAME", length=64)
	private String bankAccountName;

	@Basic
	@Column(name="BANK_CARD_NO", length=64)
	private String bankCardNo;

	@Basic
	@Column(name="BUSINESS_COVER", length=64)
	private String businessCover;

	@Basic
	@Column(name="BUSINESS_SCOPE", length=256)
	private String businessScope;

	@Basic
	@Column(name="BUSINESS_TYPE", columnDefinition="INT")
	private int businessType;

	@Basic
	private boolean ccir;

	@Basic
	@Column(name="CITY_CODE", length=64)
	private String cityCode;

	@Basic
	@Column(name="CITY_NAME", length=64)
	private String cityName;

	@Basic
	@Column(name="COMPANY_TYPE", columnDefinition="INT")
	private int companyType;

	@Basic
	@Column(length=60)
	private String corporation;

	@Basic
	@Column(name="CUSTOMER_CODE", length=20)
	private String customerCode;

	@Basic
	@Column(name="CUSTOMER_NAME", length=60)
	private String customerName;

	@Basic
	@Column(name="CUSTOMER_TYPE", columnDefinition="INT")
	private int customerType;

	@Basic
	@Column(name="DELIVERY_TYPE", columnDefinition="INT")
	private int deliveryType;

	@Basic
	@Column(name="EMPLOYEE_NUM", columnDefinition="INT")
	private int employeeNum;

	@Basic
	@Column(length=20)
	private String fax;

	@Basic
	@Column(name="FREEZER_AREA")
	private double freezerArea;

	@Basic
	@Column(name="FREEZER_VOLUME")
	private double freezerVolume;

	@Basic
	@Column(name="HAS_CAR")
	private boolean hasCar;

	@Basic
	@Column(name="HAS_QMS")
	private boolean hasQms;

	@Basic
	@Column(name="HAS_WH")
	private boolean hasWh;

	@Basic
	@Column(name="IMAGE_BANK", length=1024)
	private String imageBank;

	@Basic
	@Column(name="IMAGE_COLD", length=1024)
	private String imageCold;

	@Basic
	@Column(name="IMAGE_LICENSE", length=1024)
	private String imageLicense;

	@Basic
	@Column(name="IMAGE_LOGO", length=1024)
	private String imageLogo;

	@Basic
	@Column(name="IMAGE_ORGAN", length=1024)
	private String imageOrgan;

	@Basic
	@Column(name="IMAGE_POLICY", length=1024)
	private String imagePolicy;

	@Basic
	@Column(name="IMAGE_TAX", length=1024)
	private String imageTax;

	@Basic
	@Column(name="IMAGE_TRANSPORT", length=1024)
	private String imageTransport;

	@Basic
	@Column(name="IMAGE_WAREHOUSE", length=1024)
	private String imageWarehouse;

	@Basic
	@Column(name="INDUSTRY_EXPERIENCE", length=64)
	private String industryExperience;

	@Basic
	@Column(name="INVOICE_TYPE", columnDefinition="INT")
	private int invoiceType;

	@Basic
	@Column(columnDefinition="FLOAT")
	private float latitude;

	@Basic
	@Column(columnDefinition="FLOAT")
	private float longitude;

	@Basic
	@Column(name="NETWORK_NUM", columnDefinition="INT")
	private int networkNum;

	@Basic
	@Column(name="OFFICE_ADDRESS", length=256)
	private String officeAddress;

	@Basic
	@Column(name="ORGANIZATION_NO", length=60)
	private String organizationNo;

	@Basic
	@Column(name="OWNCAR_NUM", columnDefinition="INT")
	private int owncarNum;

	@Basic
	@Column(length=20)
	private String phone;

	@Basic
	@Column(name="POSTAL_CODE", length=20)
	private String postalCode;

	@Basic
	@Column(name="PRODUCT_LIFE", length=64)
	private String productLife;

	@Basic
	@Column(name="PRODUCT_PROCESSING")
	private boolean productProcessing;

	@Basic
	@Column(name="PRODUCTION_LICENSE", length=64)
	private String productionLicense;

	@Basic
	@Column(length=2048)
	private String profile;

	@Basic
	@Column(name="PROVINCE_CODE", length=64)
	private String provinceCode;

	@Basic
	@Column(name="PROVINCE_NAME", length=64)
	private String provinceName;

	@Basic
	@Column(name="PROXY_AREA", length=64)
	private String proxyArea;

	@Basic
	@Column(name="PROXY_DEADLINE")
	@Temporal(TemporalType.DATE)
	private Date proxyDeadline;

	@Basic
	@Column(name="PROXY_NO", length=64)
	private String proxyNo;

	@Basic
	@Column(name="PY_CODE", length=40)
	private String pyCode;

	@Basic
	@Column(name="REFRIGERAT_NUM", columnDefinition="INT")
	private int refrigeratNum;

	@Basic
	@Column(name="REGISTER_ADDRESS", length=256)
	private String registerAddress;

	@Basic
	@Column(name="REGISTER_CAPITAL", length=64)
	private String registerCapital;

	@Basic
	@Column(name="REGISTER_NO", length=64)
	private String registerNo;

	@Basic
	@Column(length=256)
	private String remark;

	@Basic
	@Column(name="SUPPLY_INDUSTRY", length=64)
	private String supplyIndustry;

	@Basic
	private double taxrate;

	@Basic
	@Column(name="TFN_NO", length=64)
	private String tfnNo;

	@Basic
	@Column(length=256)
	private String website;

	@Basic
	@Column(name="WH_AREA")
	private double whArea;

	@Basic
	@Column(name="WH_NETWORK_NUM", columnDefinition="INT")
	private int whNetworkNum;

	@Basic
	@Column(name="WH_NUM", columnDefinition="INT")
	private int whNum;

	@Basic
	@Column(name="WH_VOLUME")
	private double whVolume;
}