package org.mytms.customer.domain;

import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="crm_customer_relationship")
public class CustomerRelationship extends OrgAssignedEntity<Long, CustomerRelationship> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="CCR_CUSTOMER_CODE", length=64)
	private String ccrCustomerCode;

	@Basic
	@Column(name="CCR_CUSTOMER_NAME", length=64)
	private String ccrCustomerName;

	@Basic
	@Column(name="CCR_CUSTOMER_PM_CODE", length=64)
	private String ccrCustomerPmCode;

	@Basic
	@Column(name="CCR_PARENT_PM_CODE", length=64)
	private String ccrParentPmCode;

	@Basic
	@Column(name="CCR_REMARK", length=256)
	private String ccrRemark;

	@Id
	private long id;

	@Basic
	@Column(name="PM_CODE", length=64)
	private String pmCode;
}