package org.mytms.customer.domain;

import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="driver")
public class Driver extends OrgAssignedEntity<Long, Driver> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="AUDIT_STATUS", columnDefinition="INT")
	private int auditStatus;

	@Basic
	@Column(length=20)
	private String auditor;

	@Basic
	@Column(length=256)
	private String domicle;

	@Basic
	@Column(name="DRIVER_NAME", length=40)
	private String driverName;

	@Basic
	@Column(name="DRIVER_NO", length=64)
	private String driverNo;

	@Basic
	@Column(name="DRIVERCARD_PHOTO", length=256)
	private String drivercardPhoto;

	@Basic
	@Column(name="DRIVING_TYPE", columnDefinition="INT")
	private int drivingType;

	@Basic
	@Column(name="IDENTIFY_PHOTO", length=256)
	private String identifyPhoto;

	@Basic
	@Column(name="LICENSE_PERIOD_TYPE", columnDefinition="INT")
	private int licensePeriodType;

	@Basic
	@Column(length=20)
	private String mobile;

	@Basic
	@Column(name="OTHER_PHOTO", length=256)
	private String otherPhoto;

	@Basic
	@Column(name="PERMANENT_LOCATION", length=256)
	private String permanentLocation;

	@Basic
	@Column(length=256)
	private String remark;

	@Basic
	private boolean sex;
}