package org.mytms.customer.domain;

import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="crm_equipment")
public class Equipment extends OrgAssignedEntity<Long, Equipment> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="CE_AUDIT_STATUS", length=32)
	private String ceAuditStatus;

	@Basic
	@Column(name="CE_CUSTOMER_CODE", length=64)
	private String ceCustomerCode;

	@Basic
	@Column(name="CE_CUSTOMER_NAME", length=64)
	private String ceCustomerName;

	@Basic
	@Column(name="CE_CUSTOMER_PM_CODE", length=64)
	private String ceCustomerPmCode;

	@Basic
	@Column(name="CE_EQUIPMENT_NAME", length=64)
	private String ceEquipmentName;

	@Basic
	@Column(name="CE_EQUIPMENT_NO", length=64)
	private String ceEquipmentNo;

	@Basic
	@Column(name="CE_MANUFACTURER", length=64)
	private String ceManufacturer;

	@Basic
	@Column(name="CE_OUT_NO", length=64)
	private String ceOutNo;

	@Basic
	@Column(name="CE_REMARK", length=256)
	private String ceRemark;

	@Basic
	@Column(name="CE_SERIAL_NO", length=64)
	private String ceSerialNo;

	@Basic
	@Column(name="CE_SPEC_MODEL", length=64)
	private String ceSpecModel;

	@Basic
	@Column(name="CE_TYPE", length=64)
	private String ceType;

	@Id
	private long id;

	@Basic
	@Column(name="PM_CODE", length=64)
	private String pmCode;
}