package org.mytms.customer.domain;

import java.util.*;
import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="crm_customer_insurance")
public class Insurance extends OrgAssignedEntity<Long, Insurance> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="CI_CUSTOMER_PM_CODE", length=64)
	private String ciCustomerPmCode;

	@Basic
	@Column(name="CI_INSURANCE_COMPANY", length=64)
	private String ciInsuranceCompany;

	@Basic
	@Column(name="CI_INSURANCE_DEADLINE")
	private Date ciInsuranceDeadline;

	@Basic
	@Column(name="CI_INSURANCE_MAXAMOUNT", length=64)
	private String ciInsuranceMaxamount;

	@Basic
	@Column(name="CI_INSURANCE_NO", length=64)
	private String ciInsuranceNo;

	@Basic
	@Column(name="CI_REMARK", length=256)
	private String ciRemark;

	@Id
	private long id;

	@Basic
	@Column(name="PM_CODE", length=64)
	private String pmCode;
}