package org.mytms.customer.domain;

import java.util.*;
import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="insurance")
public class Insurance extends OrgAssignedEntity<Long, Insurance> {
    private static final long serialVersionUID = 1L;

    @Basic
    private Date deadline;

    @Basic
    @Column(name="DRIVER_POLICY", columnDefinition="INT")
    private Integer driverPolicy;

    @Basic
    @Column(name="PASSENGER_POLICY", columnDefinition="INT")
    private Integer passengerPolicy;

    @Basic
    @Column(name="POLICY_NO", length=64)
    private String policyNo;

    @Basic
    @Column(name="POLICY_TYPE", length=64)
    private String policyType;

    @Basic
    @Column(length=256)
    private String remark;

    @Basic
    @Column(length=64)
    private String supplier;

    @Basic
    @Column(name="TEMPERTURE_POLICY", columnDefinition="INT")
    private Integer temperturePolicy;

    @Basic
    @Column(name="THIRD_PARTY_POLICY", columnDefinition="INT")
    private Integer thirdPartyPolicy;

    @Basic
    @Column(name="TOTAL_POLICY", columnDefinition="INT")
    private Integer totalPolicy;

    @ManyToOne(targetEntity = Vehicle.class, fetch = FetchType.LAZY)
    @JoinColumn(foreignKey = @ForeignKey(ConstraintMode.NO_CONSTRAINT), name = "vehicle_id")
    private Vehicle vehicle;

    @ManyToOne(targetEntity = Warehouse.class, fetch = FetchType.LAZY)
    @JoinColumn(foreignKey = @ForeignKey(ConstraintMode.NO_CONSTRAINT), name = "warehouse_id")
    private Warehouse warehouse;
}