package org.mytms.customer.domain;

import javax.persistence.*;

import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "line")
public class Line extends OrgAssignedEntity<Long, Line> {
    private static final long serialVersionUID = 1L;

    @Basic
    @Column(name = "BUSINESS_TYPE", columnDefinition = "INT")
    private Integer businessType;

    @Basic
    @Column(name = "DELIVERY_AREA", length = 256)
    private String deliveryArea;

    @Basic
    @Column(name = "DEPARTURE_CODE", length = 64)
    private String departureCode;

    @Basic
    @Column(name = "DEPARTURE_NAME", length = 64)
    private String departureName;

    @Basic
    @Column(name = "DESTINATION_CODE", length = 64)
    private String destinationCode;

    @Basic
    @Column(name = "DESTINATION_NAME", length = 64)
    private String destinationName;

    @Basic
    @Column(length = 256)
    private String remark;
}