package org.mytms.customer.domain;

import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="crm_customer_line")
public class Line extends OrgAssignedEntity<Long, Line> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="CCL_BUSINESS_TYPE", length=64)
	private String cclBusinessType;

	@Basic
	@Column(name="CCL_CUSTOMER_PM_CODE", length=64)
	private String cclCustomerPmCode;

	@Basic
	@Column(name="CCL_DELIVERY_AREA", length=256)
	private String cclDeliveryArea;

	@Basic
	@Column(name="CCL_DEPARTURE_CODE", length=64)
	private String cclDepartureCode;

	@Basic
	@Column(name="CCL_DEPARTURE_NAME", length=64)
	private String cclDepartureName;

	@Basic
	@Column(name="CCL_DESTINATION_CODE", length=64)
	private String cclDestinationCode;

	@Basic
	@Column(name="CCL_DESTINATION_NAME", length=64)
	private String cclDestinationName;

	@Basic
	@Column(length=256)
	private String cclremark;

	@Id
	private long id;

	@Basic
	@Column(name="PM_CODE", length=64)
	private String pmCode;
}