package org.mytms.customer.domain;

import java.util.*;
import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="crm_vehicle")
public class Vehicle extends OrgAssignedEntity<Long, Vehicle> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="CV_APPROED_LOAD")
	private double cvApproedLoad;

	@Basic
	@Column(name="CV_AUDIT_STATUS", length=64)
	private String cvAuditStatus;

	@Basic
	@Column(name="CV_AUDITOR", length=64)
	private String cvAuditor;

	@Basic
	@Column(name="CV_BRAND_MODEL", length=64)
	private String cvBrandModel;

	@Basic
	@Column(name="CV_BUSINESS_POLICY", length=64)
	private String cvBusinessPolicy;

	@Basic
	@Column(name="CV_CAR_OPERATION_PIC", length=256)
	private String cvCarOperationPic;

	@Basic
	@Column(name="CV_CAR_OWNER", length=64)
	private String cvCarOwner;

	@Basic
	@Column(name="CV_CAR_PIC", length=256)
	private String cvCarPic;

	@Basic
	@Column(name="CV_CARD", length=64)
	private String cvCard;

	@Basic
	@Column(name="CV_CARRIAGE_FORMAT", length=64)
	private String cvCarriageFormat;

	@Basic
	@Column(name="CV_COMPANY", length=64)
	private String cvCompany;

	@Basic
	@Column(name="CV_CUSTOMER_CODE", length=64)
	private String cvCustomerCode;

	@Basic
	@Column(name="CV_CUSTOMER_NAME", length=64)
	private String cvCustomerName;

	@Basic
	@Column(name="CV_CUSTOMER_PM_CODE", length=64)
	private String cvCustomerPmCode;

	@Basic
	@Column(name="CV_DRIVING_PIC", length=256)
	private String cvDrivingPic;

	@Basic
	@Column(name="CV_ENGINE_NO", length=64)
	private String cvEngineNo;

	@Basic
	@Column(name="CV_EQUIPMENT_NUM", columnDefinition="INT")
	private int cvEquipmentNum;

	@Basic
	@Column(name="CV_GPS_MANUFACTURER", length=64)
	private String cvGpsManufacturer;

	@Basic
	@Column(name="CV_HYGROSCOPE_MANUFACTURER", length=64)
	private String cvHygroscopeManufacturer;

	@Basic
	@Column(name="CV_IS_GPS", length=64)
	private String cvIsGps;

	@Basic
	@Column(name="CV_IS_HYGROSCOP", length=64)
	private String cvIsHygroscop;

	@Basic
	@Column(name="CV_IS_LOAN", length=64)
	private String cvIsLoan;

	@Basic
	@Column(name="CV_IS_THERMOSTAT", length=64)
	private String cvIsThermostat;

	@Basic
	@Column(name="CV_MAX_TEMP", length=64)
	private String cvMaxTemp;

	@Basic
	@Column(name="CV_MIN_TEMP", length=64)
	private String cvMinTemp;

	@Basic
	@Column(name="CV_OPERATE_NO", length=64)
	private String cvOperateNo;

	@Basic
	@Column(name="CV_REGDATE")
	@Temporal(TemporalType.DATE)
	private Date cvRegdate;

	@Basic
	@Column(name="CV_REMARK", length=256)
	private String cvRemark;

	@Basic
	@Column(name="CV_SERVICE_LIFE", columnDefinition="INT")
	private int cvServiceLife;

	@Basic
	@Column(name="CV_STRONG_POLICY", length=64)
	private String cvStrongPolicy;

	@Basic
	@Column(name="CV_THERMOSTAT_MANUFACTURER", length=64)
	private String cvThermostatManufacturer;

	@Basic
	@Column(name="CV_VEHICLE_LENGTH", length=64)
	private String cvVehicleLength;

	@Basic
	@Column(name="CV_VEHICLE_OWNERSHIP", length=64)
	private String cvVehicleOwnership;

	@Basic
	@Column(name="CV_VEHICLE_TYPE", length=64)
	private String cvVehicleType;

	@Basic
	@Column(name="CV_VIN", length=64)
	private String cvVin;

	@Basic
	@Column(name="CV_WARRANT_PIC", length=1024)
	private String cvWarrantPic;

	@Basic
	@Column(name="CV_WEIGHT_LOAD")
	private double cvWeightLoad;

	@Id
	@Column(columnDefinition="BIGINT UNSIGNED")
	private long id;

	@Basic
	@Column(name="PM_CODE", length=64)
	private String pmCode;
}