package org.mytms.customer.domain;

import java.util.*;
import javax.persistence.*;

import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "vehicle")
public class Vehicle extends OrgAssignedEntity<Long, Vehicle> {
    private static final long serialVersionUID = 1L;

    @Basic
    @Column(name = "APPROED_LOAD")
    private Double approedLoad;

    @Basic
    @Column(name = "AUDIT_STATUS", columnDefinition = "INT")
    private Integer auditStatus;

    @Basic
    @Column(length = 64)
    private String auditor;

    @Basic
    @Column(name = "BRAND_MODEL", length = 64)
    private String brandModel;

    @Basic
    @Column(name = "BUSINESS_POLICY", length = 64)
    private String businessPolicy;

    @Basic
    @Column(name = "CAR_OWNER", length = 64)
    private String carOwner;

    @Basic
    @Column(name = "CARD_NO", length = 64)
    private String cardNo;

    @Basic
    @Column(name = "CARRIAGE_FORMAT", length = 64)
    private String carriageFormat;

    @Basic
    @Column(length = 64)
    private String company;

    @Basic
    @Column(name = "ENGINE_NO", length = 64)
    private String engineNo;

    @Basic
    @Column(name = "EQUIPMENT_NUM", columnDefinition = "INT")
    private Integer equipmentNum;

    @Basic
    private Boolean gps;

    @Basic
    @Column(name = "GPS_MANUFACTURER_ID")
    private Long gpsManufacturerId;

    @Basic
    @Column(name = "HAS_HYGROSCOP")
    private Boolean hasHygroscop;

    @Basic
    @Column(name = "HAS_THERMOSTAT")
    private Boolean hasThermostat;

    @Basic
    @Column(name = "HYGROSCOPE_MANUFACTURER_ID", length = 64)
    private String hygroscopeManufacturerId;

    @Basic
    @Column(name = "IMG_CAR", length = 256)
    private String imgCar;

    @Basic
    @Column(name = "IMG_CAR_OPERATION", length = 256)
    private String imgCarOperation;

    @Basic
    @Column(name = "IMG_DRIVING", length = 256)
    private String imgDriving;

    @Basic
    @Column(name = "IMG_WARRANT", length = 1024)
    private String imgWarrant;

    @Basic
    private Boolean loan;

    @Basic
    @Column(name = "MAX_TEMP", columnDefinition = "INT")
    private Integer maxTemp;

    @Basic
    @Column(name = "MIN_TEMP", columnDefinition = "INT")
    private Integer minTemp;

    @Basic
    @Column(name = "OPERATE_NO", length = 64)
    private String operateNo;

    @Basic
    @Column(name = "OWNER_TYPE", columnDefinition = "INT")
    private Integer ownerType;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date regdate;

    @Basic
    @Column(length = 256)
    private String remark;

    @Basic
    @Column(name = "SERVICE_LIFE", columnDefinition = "INT")
    private Integer serviceLife;

    @Basic
    @Column(name = "STRONG_POLICY", length = 64)
    private String strongPolicy;

    @Basic
    @Column(name = "THERMOSTAT_MANUFACTURER_ID")
    private Long thermostatManufacturerId;

    @Basic
    @Column(name = "VEHICLE_LENGTH", columnDefinition = "FLOAT")
    private Float vehicleLength;

    @Basic
    @Column(name = "VEHICLE_TYPE", columnDefinition = "INT")
    private Integer vehicleType;

    @Basic
    @Column(length = 64)
    private String vin;

    @Basic
    @Column(name = "WEIGHT_LOAD")
    private Double weightLoad;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicle", targetEntity = Insurance.class)
    private List<Insurance> insurances;
}