package org.mytms.customer.domain;

import java.util.*;
import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="vehicle")
public class Vehicle extends OrgAssignedEntity<Long, Vehicle> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="APPROED_LOAD")
	private double approedLoad;

	@Basic
	@Column(name="AUDIT_STATUS_TYPE", columnDefinition="INT")
	private int auditStatusType;

	@Basic
	@Column(length=64)
	private String auditor;

	@Basic
	@Column(name="BRAND_MODEL", length=64)
	private String brandModel;

	@Basic
	@Column(name="BUSINESS_POLICY", length=64)
	private String businessPolicy;

	@Basic
	@Column(name="CAR_OPERATION_PIC", length=256)
	private String carOperationPic;

	@Basic
	@Column(name="CAR_OWNER", length=64)
	private String carOwner;

	@Basic
	@Column(name="CAR_PIC", length=256)
	private String carPic;

	@Basic
	@Column(name="CARD_NO", length=64)
	private String cardNo;

	@Basic
	@Column(name="CARRIAGE_FORMAT", length=64)
	private String carriageFormat;

	@Basic
	@Column(length=64)
	private String company;

	@Basic
	@Column(name="DRIVING_PIC", length=256)
	private String drivingPic;

	@Basic
	@Column(name="ENGINE_NO", length=64)
	private String engineNo;

	@Basic
	@Column(name="EQUIPMENT_NUM", columnDefinition="INT")
	private int equipmentNum;

	@Basic
	private boolean gps;

	@Basic
	@Column(name="GPS_MANUFACTURER", length=64)
	private String gpsManufacturer;

	@Basic
	@Column(name="HAS_HYGROSCOP")
	private boolean hasHygroscop;

	@Basic
	@Column(name="HAS_THERMOSTAT")
	private boolean hasThermostat;

	@Basic
	@Column(name="HYGROSCOPE_MANUFACTURER", length=64)
	private String hygroscopeManufacturer;

	@Basic
	private boolean loan;

	@Basic
	@Column(name="MAX_TEMP", columnDefinition="INT")
	private int maxTemp;

	@Basic
	@Column(name="MIN_TEMP", columnDefinition="INT")
	private int minTemp;

	@Basic
	@Column(name="OPERATE_NO", length=64)
	private String operateNo;

	@Basic
	@Column(name="OWNER_TYPE", columnDefinition="INT")
	private int ownerType;

	@Basic
	@Temporal(TemporalType.DATE)
	private Date regdate;

	@Basic
	@Column(length=256)
	private String remark;

	@Basic
	@Column(name="SERVICE_LIFE", columnDefinition="INT")
	private int serviceLife;

	@Basic
	@Column(name="STRONG_POLICY", length=64)
	private String strongPolicy;

	@Basic
	@Column(name="THERMOSTAT_MANUFACTURER", length=64)
	private String thermostatManufacturer;

	@Basic
	@Column(name="VEHICLE_LENGTH", columnDefinition="FLOAT")
	private float vehicleLength;

	@Basic
	@Column(name="VEHICLE_TYPE", columnDefinition="INT")
	private int vehicleType;

	@Basic
	@Column(length=64)
	private String vin;

	@Basic
	@Column(name="WARRANT_PIC", length=1024)
	private String warrantPic;

	@Basic
	@Column(name="WEIGHT_LOAD")
	private double weightLoad;
}