package org.mytms.customer.domain;

import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="warehouse")
public class Warehouse extends OrgAssignedEntity<Long, Warehouse> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(length=256)
	private String address;

	@Basic
	@Column(name="AREA_CODE", length=64)
	private String areaCode;

	@Basic
	@Column(name="AREA_NAME", length=64)
	private String areaName;

	@Basic
	@Column(name="CITY_CODE", length=64)
	private String cityCode;

	@Basic
	@Column(name="CITY_NAME", length=64)
	private String cityName;

	@Basic
	@Column(name="CUSTOMER_CODE", length=64)
	private String customerCode;

	@Basic
	@Column(name="CUSTOMER_NAME", length=64)
	private String customerName;

	@Basic
	@Column(name="CUSTOMER_PM_CODE", length=64)
	private String customerPmCode;

	@Basic
	@Column(name="FIRE_ACCEPT", length=256)
	private String fireAccept;

	@Basic
	@Column(length=64)
	private String firefight;

	@Basic
	@Column(name="GRADE_LABEL", length=64)
	private String gradeLabel;

	@Basic
	@Column(columnDefinition="FLOAT")
	private float latitude;

	@Basic
	@Column(columnDefinition="FLOAT")
	private float longitude;

	@Basic
	@Column(name="MATCH_EQUIPMENT", length=64)
	private String matchEquipment;

	@Basic
	@Column(name="OPERATE_PERMIT", length=256)
	private String operatePermit;

	@Basic
	@Column(name="PROPERTY_PHOTO", length=256)
	private String propertyPhoto;

	@Basic
	@Column(name="PROVINCE_CODE", length=64)
	private String provinceCode;

	@Basic
	@Column(name="PROVINCE_NAME", length=64)
	private String provinceName;

	@Basic
	@Column(length=256)
	private String remark;

	@Basic
	@Column(name="RENTAL_AGREEMENT", length=256)
	private String rentalAgreement;

	@Basic
	@Column(length=64)
	private String security;

	@Basic
	@Column(name="WH_AREA", columnDefinition="FLOAT")
	private float whArea;

	@Basic
	@Column(name="WH_CUBAGE", columnDefinition="FLOAT")
	private float whCubage;

	@Basic
	@Column(name="WH_GROUND", columnDefinition="FLOAT")
	private float whGround;

	@Basic
	@Column(name="WH_HEIGHT", columnDefinition="FLOAT")
	private float whHeight;

	@Basic
	@Column(name="WH_NAME", length=64)
	private String whName;

	@Basic
	@Column(name="WH_NO", length=64)
	private String whNo;

	@Basic
	@Column(name="WH_OPERATE")
	private boolean whOperate;

	@Basic
	@Column(name="WH_PHOTO", length=256)
	private String whPhoto;

	@Basic
	@Column(name="WH_PLAN", length=256)
	private String whPlan;

	@Basic
	@Column(name="WH_STRUCTURE", length=64)
	private String whStructure;

	@Basic
	@Column(name="WH_TYPE", columnDefinition="INT")
	private int whType;
}