package org.mytms.customer.domain;

import javax.persistence.*;

import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "warehouse")
public class Warehouse extends OrgAssignedEntity<Long, Warehouse> {
    private static final long serialVersionUID = 1L;

    @Basic
    @Column(length = 256)
    private String address;

    @Basic
    private Double area;

    @Basic
    @Column(name = "AREA_CODE", length = 64)
    private String areaCode;

    @Basic
    @Column(name = "AREA_NAME", length = 64)
    private String areaName;

    @Basic
    @Column(name = "CITY_CODE", length = 64)
    private String cityCode;

    @Basic
    @Column(name = "CITY_NAME", length = 64)
    private String cityName;

    @Basic
    @Column(length = 64)
    private String code;

    @Basic
    private Double cubage;

    @Basic
    @Column(length = 64)
    private String firefight;

    @Basic
    @Column(name = "GRADE_LABEL", length = 64)
    private String gradeLabel;

    @Basic
    @Column(name = "GROUND_TYPE", columnDefinition = "INT")
    private Integer groundType;

    @Basic
    @Column(name = "HEIGHT_LEVEL", columnDefinition = "INT")
    private Integer heightLevel;

    @Basic
    @Column(name = "IMG_FIRE_ACCEPT", length = 256)
    private String imgFireAccept;

    @Basic
    @Column(name = "IMG_OPERATE_PERMIT", length = 256)
    private String imgOperatePermit;

    @Basic
    @Column(name = "IMG_PLAN", length = 256)
    private String imgPlan;

    @Basic
    @Column(name = "IMG_PROPERTY", length = 256)
    private String imgProperty;

    @Basic
    @Column(name = "IMG_RENTAL_AGREEMENT", length = 256)
    private String imgRentalAgreement;

    @Basic
    @Column(name = "IMG_WAREHOUSE", length = 256)
    private String imgWarehouse;

    @Basic
    @Column(columnDefinition = "FLOAT")
    private Float latitude;

    @Basic
    @Column(columnDefinition = "FLOAT")
    private Float longitude;

    @Basic
    @Column(name = "MATCH_EQUIPMENT", length = 64)
    private String matchEquipment;

    @Basic
    @Column(length = 64)
    private String name;

    @Basic
    private Boolean operate;

    @Basic
    @Column(name = "PROVINCE_CODE", length = 64)
    private String provinceCode;

    @Basic
    @Column(name = "PROVINCE_NAME", length = 64)
    private String provinceName;

    @Basic
    @Column(length = 256)
    private String remark;

    @Basic
    @Column(length = 64)
    private String security;

    @Basic
    @Column(length = 64)
    private String struct;

    @Basic
    @Column(name = "WAREHOUSE_TYPE", columnDefinition = "INT")
    private Integer warehouseType;
}