package org.mytms.customer.domain;

import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

import java.util.List;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="warehouse")
public class Warehouse extends OrgAssignedEntity<Long, Warehouse> {
    private static final long serialVersionUID = 1L;

    @Basic
    @Column(length=256)
    private String address;

    @Basic
    private Double area;

    @Basic
    @Column(name="AREA_CODE", length=64)
    private String areaCode;

    @Basic
    @Column(name="AREA_NAME", length=64)
    private String areaName;

    @Basic
    @Column(name="BALANCE_PERIOD", columnDefinition="INT")
    private Integer balancePeriod;

    @Basic
    @Column(name="BALANCE_TYPE", columnDefinition="INT")
    private Integer balanceType;

    @Basic
    @Column(name="CITY_CODE", length=64)
    private String cityCode;

    @Basic
    @Column(name="CITY_NAME", length=64)
    private String cityName;

    @Basic
    @Column(length=64)
    private String code;

    @Basic
    @Column(name="COOPERATE_VEHICLE_TYPE", columnDefinition="INT")
    private Integer cooperateVehicleType;

    @Basic
    private Double cubage;

    @Basic
    @Column(name="DISTRIBUTION_ABILITY", columnDefinition="INT")
    private Integer distributionAbility;

    @Basic
    @Column(columnDefinition="INT")
    private Integer firefight;

    @Basic
    @Column(name="GRADE_LABEL", columnDefinition="INT")
    private Integer gradeLabel;

    @Basic
    @Column(name="GROUND_TYPE", columnDefinition="INT")
    private Integer groundType;

    @Basic
    @Column(name="HAS_ALLOCATION")
    private Boolean hasAllocation;

    @Basic
    @Column(name="HAS_DAMPNESS")
    private Boolean hasDampness;

    @Basic
    @Column(name="HAS_FOOD_LICENSE")
    private Boolean hasFoodLicense;

    @Basic
    @Column(name="HAS_GSP")
    private Boolean hasGsp;

    @Basic
    @Column(name="HAS_LOAD")
    private Boolean hasLoad;

    @Basic
    @Column(name="HAS_PLATFORM")
    private Boolean hasPlatform;

    @Basic
    @Column(name="HAS_RACK")
    private Boolean hasRack;

    @Basic
    @Column(name="REFRIGERATION_PLANT")
    private Integer refrigerationPlant;

    @Basic
    @Column(name="HAS_TEMPERATURE")
    private Boolean hasTemperature;

    @Basic
    @Column(name="HAS_VIDEO")
    private Boolean hasVideo;

    @Basic
    @Column(name="HAS_WMS", columnDefinition="INT")
    private Integer hasWms;

    @Basic
    @Column(name="HEIGHT_LEVEL", columnDefinition="INT")
    private Integer heightLevel;

    @Basic
    @Column(name="IMG_FIRE_ACCEPT", length=256)
    private String imgFireAccept;

    @Basic
    @Column(name="IMG_OPERATE_PERMIT", length=256)
    private String imgOperatePermit;

    @Basic
    @Column(name="IMG_PLAN", length=256)
    private String imgPlan;

    @Basic
    @Column(name="IMG_PROPERTY", length=256)
    private String imgProperty;

    @Basic
    @Column(name="IMG_RENTAL_AGREEMENT", length=256)
    private String imgRentalAgreement;

    @Basic
    @Column(name="IMG_WAREHOUSE", length=256)
    private String imgWarehouse;

    @Basic
    @Column(columnDefinition="FLOAT")
    private Float latitude;

    @Basic
    @Column(columnDefinition="FLOAT")
    private Float longitude;

    @Basic
    @Column(name="MATCH_EQUIPMENT", columnDefinition="INT")
    private Integer matchEquipment;

    @Basic
    @Column(name="MIN_CHARGE")
    private Double minCharge;

    @Basic
    @Column(length=64)
    private String name;

    @Basic
    private Boolean operate;

    @Basic
    @Column(name="OPERATION_FEE_DETAIL")
    private Double operationFeeDetail;

    @Basic
    @Column(name="OPERATION_FEE_TYPE", length=50)
    private String operationFeeType;

    @Basic
    @Column(name="PICKUP_AREA", length=256)
    private String pickupArea;

    @Basic
    @Column(name="PROVINCE_CODE", length=64)
    private String provinceCode;

    @Basic
    @Column(name="PROVINCE_NAME", length=64)
    private String provinceName;

    @Basic
    @Column(name="REFRIGERATED_VEHICLES", columnDefinition="INT")
    private Integer refrigeratedVehicles;

    @Basic
    @Column(length=256)
    private String remark;

    @Basic
    @Column(columnDefinition="INT")
    private Integer security;

    @Basic
    @Column(name="STORAGE_BALANCE_TYPE", columnDefinition="INT")
    private Integer storageBalanceType;

    @Basic
    @Column(name="STORAGE_CHARGE_WAY", columnDefinition="INT")
    private Integer storageChargeWay;

    @Basic
    @Column(name="STORAGE_PRICE_DETAIL")
    private Double storagePriceDetail;

    @Basic
    @Column(columnDefinition="INT")
    private Integer struct;

    @Basic
    @Column(name="TEAM_NAME", length=256)
    private String teamName;

    @Basic
    @Column(columnDefinition="INT")
    private Integer vehicles;

    @Basic
    @Column(name="WAREHOUSE_TYPE", length=50)
    private String warehouseType;

    @Basic
    @Column(name = "STORAGE_CHARGE_OTHER_WAY", length = 256)
    private String storageChargeOtherWay;

    @Basic
    @Column(name = "OPERATION_OTHER_FEE")
    private Double operationOtherFee;

    @Basic
    @Column(name = "AUDIT_STATUS", columnDefinition = "INT")
    private Integer auditStatus;

    @Basic
    @Column(length = 64)
    private String auditor;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouse", targetEntity = Insurance.class)
    private List<Insurance> insurances;
}