package org.mytms.crm.domain;

import java.util.*;
import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="crm_customer")
public class Customer extends OrgAssignedEntity<Long, Customer> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="CC_ABBREV", length=64)
	private String ccAbbrev;

	@Basic
	@Column(name="CC_AREA_CODE", length=64)
	private String ccAreaCode;

	@Basic
	@Column(name="CC_AREA_NAME", length=64)
	private String ccAreaName;

	@Basic
	@Column(name="CC_AUDIT_STATUS", length=64)
	private String ccAuditStatus;

	@Basic
	@Column(name="CC_AUDITOR", length=64)
	private String ccAuditor;

	@Basic
	@Column(name="CC_BANK_ACCOUNT", length=64)
	private String ccBankAccount;

	@Basic
	@Column(name="CC_BANK_ACCOUNT_NAME", length=64)
	private String ccBankAccountName;

	@Basic
	@Column(name="CC_BANK_CARD_NO", length=64)
	private String ccBankCardNo;

	@Basic
	@Column(name="CC_BUSINESS_COVER", length=64)
	private String ccBusinessCover;

	@Basic
	@Column(name="CC_BUSINESS_SCOPE", length=256)
	private String ccBusinessScope;

	@Basic
	@Column(name="CC_BUSINESS_TYPE", length=64)
	private String ccBusinessType;

	@Basic
	@Column(name="CC_CITY_CODE", length=64)
	private String ccCityCode;

	@Basic
	@Column(name="CC_CITY_NAME", length=64)
	private String ccCityName;

	@Basic
	@Column(name="CC_COMPANY_TYPE", length=64)
	private String ccCompanyType;

	@Basic
	@Column(name="CC_CORPORATION", length=64)
	private String ccCorporation;

	@Basic
	@Column(name="CC_CUSTOMER_CODE", length=64)
	private String ccCustomerCode;

	@Basic
	@Column(name="CC_CUSTOMER_NAME", length=64)
	private String ccCustomerName;

	@Basic
	@Column(name="CC_CUSTOMER_TYPE", length=64)
	private String ccCustomerType;

	@Basic
	@Column(name="CC_DELIVERY_TYPE", length=64)
	private String ccDeliveryType;

	@Basic
	@Column(name="CC_EMPLOYEE_NUM", columnDefinition="INT")
	private int ccEmployeeNum;

	@Basic
	@Column(name="CC_FAX", length=64)
	private String ccFax;

	@Basic
	@Column(name="CC_FREEZER_AREA")
	private double ccFreezerArea;

	@Basic
	@Column(name="CC_FREEZER_VOLUME")
	private double ccFreezerVolume;

	@Basic
	@Column(name="CC_HAS_CAR", length=64)
	private String ccHasCar;

	@Basic
	@Column(name="CC_HAS_QMS", length=64)
	private String ccHasQms;

	@Basic
	@Column(name="CC_HAS_WH", length=64)
	private String ccHasWh;

	@Basic
	@Column(name="CC_INDUSTRY_EXPERIENCE", length=64)
	private String ccIndustryExperience;

	@Basic
	@Column(name="CC_INVOICE_TYPE", length=64)
	private String ccInvoiceType;

	@Basic
	@Column(name="CC_IS_CCIR", length=64)
	private String ccIsCcir;

	@Basic
	@Column(name="CC_IS_PRODUCT_PROCESSING", length=64)
	private String ccIsProductProcessing;

	@Basic
	@Column(name="CC_LATITUDE", length=64)
	private String ccLatitude;

	@Basic
	@Column(name="CC_LONGITUDE", length=64)
	private String ccLongitude;

	@Basic
	@Column(name="CC_NETWORK_NUM", columnDefinition="INT")
	private int ccNetworkNum;

	@Basic
	@Column(name="CC_OFFICE_ADDRESS", length=256)
	private String ccOfficeAddress;

	@Basic
	@Column(name="CC_ORGANIZATION_NO", length=64)
	private String ccOrganizationNo;

	@Basic
	@Column(name="CC_OWNCAR_NUM", columnDefinition="INT")
	private int ccOwncarNum;

	@Basic
	@Column(name="CC_PHONE", length=64)
	private String ccPhone;

	@Basic
	@Column(name="CC_POSTAL_CODE", length=64)
	private String ccPostalCode;

	@Basic
	@Column(name="CC_PRODUCT_LIFE", length=64)
	private String ccProductLife;

	@Basic
	@Column(name="CC_PRODUCTION_LICENSE", length=64)
	private String ccProductionLicense;

	@Basic
	@Column(name="CC_PROFILE", length=2048)
	private String ccProfile;

	@Basic
	@Column(name="CC_PROVINCE_CODE", length=64)
	private String ccProvinceCode;

	@Basic
	@Column(name="CC_PROVINCE_NAME", length=64)
	private String ccProvinceName;

	@Basic
	@Column(name="CC_PROXY_AREA", length=64)
	private String ccProxyArea;

	@Basic
	@Column(name="CC_PROXY_DEADLINE")
	@Temporal(TemporalType.DATE)
	private Date ccProxyDeadline;

	@Basic
	@Column(name="CC_PROXY_NO", length=64)
	private String ccProxyNo;

	@Basic
	@Column(name="CC_PY_CODE", length=64)
	private String ccPyCode;

	@Basic
	@Column(name="CC_REFRIGERAT_NUM", columnDefinition="INT")
	private int ccRefrigeratNum;

	@Basic
	@Column(name="CC_REGISTER_ADDRESS", length=256)
	private String ccRegisterAddress;

	@Basic
	@Column(name="CC_REGISTER_CAPITAL", length=64)
	private String ccRegisterCapital;

	@Basic
	@Column(name="CC_REGISTER_NO", length=64)
	private String ccRegisterNo;

	@Basic
	@Column(name="CC_REMARK", length=256)
	private String ccRemark;

	@Basic
	@Column(name="CC_SUPPLY_INDUSTRY", length=64)
	private String ccSupplyIndustry;

	@Basic
	@Column(name="CC_TAXRATE")
	private double ccTaxrate;

	@Basic
	@Column(name="CC_TFN_NO", length=64)
	private String ccTfnNo;

	@Basic
	@Column(name="CC_WEBSITE", length=256)
	private String ccWebsite;

	@Basic
	@Column(name="CC_WH_AREA")
	private double ccWhArea;

	@Basic
	@Column(name="CC_WH_NETWORK_NUM", columnDefinition="INT")
	private int ccWhNetworkNum;

	@Basic
	@Column(name="CC_WH_NUM", columnDefinition="INT")
	private int ccWhNum;

	@Basic
	@Column(name="CC_WH_VOLUME")
	private double ccWhVolume;

	@Basic
	@Column(name="IMAGE_BANK", length=1024)
	private String imageBank;

	@Basic
	@Column(name="IMAGE_COLD", length=1024)
	private String imageCold;

	@Basic
	@Column(name="IMAGE_LICENSE", length=1024)
	private String imageLicense;

	@Basic
	@Column(name="IMAGE_LOGO", length=1024)
	private String imageLogo;

	@Basic
	@Column(name="IMAGE_ORGAN", length=1024)
	private String imageOrgan;

	@Basic
	@Column(name="IMAGE_POLICY", length=1024)
	private String imagePolicy;

	@Basic
	@Column(name="IMAGE_TAX", length=1024)
	private String imageTax;

	@Basic
	@Column(name="IMAGE_TRANSPORT", length=1024)
	private String imageTransport;

	@Basic
	@Column(name="IMAGE_WAREHOUSE", length=1024)
	private String imageWarehouse;

	@Basic
	@Column(name="PM_CODE", length=64)
	private String pmCode;
}