package org.mytms.crm.domain;

import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="crm_customer_contact")
public class CustomerContact extends OrgAssignedEntity<Long, CustomerContact> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="CCC_ADDRESS", length=256)
	private String cccAddress;

	@Basic
	@Column(name="CCC_CONTACT_NAME", length=64)
	private String cccContactName;

	@Basic
	@Column(name="CCC_CUSTOMER_PM_CODE", length=64)
	private String cccCustomerPmCode;

	@Basic
	@Column(name="CCC_EMAIL", length=128)
	private String cccEmail;

	@Basic
	@Column(name="CCC_IS_DEFAULT", length=10)
	private String cccIsDefault;

	@Basic
	@Column(name="CCC_MOBILE", length=64)
	private String cccMobile;

	@Basic
	@Column(name="CCC_POST", length=64)
	private String cccPost;

	@Basic
	@Column(name="CCC_REMARK", length=10)
	private String cccRemark;

	@Basic
	@Column(name="CCC_TAX", length=64)
	private String cccTax;

	@Basic
	@Column(name="CCC_TEL", length=64)
	private String cccTel;

	@Basic
	@Column(name="PM_CODE", length=64)
	private String pmCode;
}