package org.mytms.crm.domain;

import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="crm_driver")
public class Driver extends OrgAssignedEntity<Long, Driver> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="CD_AUDIT_STATUS", length=64)
	private String cdAuditStatus;

	@Basic
	@Column(name="CD_AUDITOR", length=64)
	private String cdAuditor;

	@Basic
	@Column(name="CD_CUSTOMER_CODE", length=64)
	private String cdCustomerCode;

	@Basic
	@Column(name="CD_CUSTOMER_NAME", length=64)
	private String cdCustomerName;

	@Basic
	@Column(name="CD_CUSTOMER_PM_CODE", length=64)
	private String cdCustomerPmCode;

	@Basic
	@Column(name="CD_DOMICLE", length=256)
	private String cdDomicle;

	@Basic
	@Column(name="CD_DRIVER_NAME", length=64)
	private String cdDriverName;

	@Basic
	@Column(name="CD_DRIVER_NO", length=64)
	private String cdDriverNo;

	@Basic
	@Column(name="CD_DRIVERCARD_PHOTO", length=256)
	private String cdDrivercardPhoto;

	@Basic
	@Column(name="CD_DRIVING_TYPE", length=64)
	private String cdDrivingType;

	@Basic
	@Column(name="CD_IDENTIFY_PHOTO", length=256)
	private String cdIdentifyPhoto;

	@Basic
	@Column(name="CD_LICENSE_PERIOD", length=64)
	private String cdLicensePeriod;

	@Basic
	@Column(name="CD_MOBILE", length=64)
	private String cdMobile;

	@Basic
	@Column(name="CD_OTHER_PHOTO", length=256)
	private String cdOtherPhoto;

	@Basic
	@Column(name="CD_PERMANENT_LOCATION", length=256)
	private String cdPermanentLocation;

	@Basic
	@Column(name="CD_REMARK", length=256)
	private String cdRemark;

	@Basic
	@Column(name="CD_SEX", length=64)
	private String cdSex;

	@Basic
	@Column(name="PM_CODE", length=64)
	private String pmCode;
}