package org.mytms.crm.domain;

import javax.persistence.*;
import org.mytms.common.domain.OrgAssignedEntity;
import lombok.*;

/**
 * Auto-generated by: OpenJPA ReverseMappingTool
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name="crm_warehouse")
public class Warehouse extends OrgAssignedEntity<Long, Warehouse> {
	private static final long serialVersionUID = 1L;

	@Basic
	@Column(name="CW_ADDRESS", length=256)
	private String cwAddress;

	@Basic
	@Column(name="CW_AREA_CODE", length=64)
	private String cwAreaCode;

	@Basic
	@Column(name="CW_AREA_NAME", length=64)
	private String cwAreaName;

	@Basic
	@Column(name="CW_CITY_CODE", length=64)
	private String cwCityCode;

	@Basic
	@Column(name="CW_CITY_NAME", length=64)
	private String cwCityName;

	@Basic
	@Column(name="CW_CUSTOMER_CODE", length=64)
	private String cwCustomerCode;

	@Basic
	@Column(name="CW_CUSTOMER_NAME", length=64)
	private String cwCustomerName;

	@Basic
	@Column(name="CW_CUSTOMER_PM_CODE", length=64)
	private String cwCustomerPmCode;

	@Basic
	@Column(name="CW_FIRE_ACCEPT", length=256)
	private String cwFireAccept;

	@Basic
	@Column(name="CW_FIREFIGHT", length=64)
	private String cwFirefight;

	@Basic
	@Column(name="CW_GRADE_LABEL", length=64)
	private String cwGradeLabel;

	@Basic
	@Column(name="CW_LATITUDE", length=64)
	private String cwLatitude;

	@Basic
	@Column(name="CW_LONGITUDE", length=64)
	private String cwLongitude;

	@Basic
	@Column(name="CW_MATCH_EQUIPMENT", length=64)
	private String cwMatchEquipment;

	@Basic
	@Column(name="CW_OPERATE_PERMIT", length=256)
	private String cwOperatePermit;

	@Basic
	@Column(name="CW_PROPERTY_PHOTO", length=256)
	private String cwPropertyPhoto;

	@Basic
	@Column(name="CW_PROVINCE_CODE", length=64)
	private String cwProvinceCode;

	@Basic
	@Column(name="CW_PROVINCE_NAME", length=64)
	private String cwProvinceName;

	@Basic
	@Column(name="CW_REMARK", length=256)
	private String cwRemark;

	@Basic
	@Column(name="CW_RENTAL_AGREEMENT", length=256)
	private String cwRentalAgreement;

	@Basic
	@Column(name="CW_SECURITY", length=64)
	private String cwSecurity;

	@Basic
	@Column(name="CW_WH_AREA", length=12)
	private String cwWhArea;

	@Basic
	@Column(name="CW_WH_CUBAGE", length=12)
	private String cwWhCubage;

	@Basic
	@Column(name="CW_WH_GROUND", length=64)
	private String cwWhGround;

	@Basic
	@Column(name="CW_WH_HEIGHT", length=64)
	private String cwWhHeight;

	@Basic
	@Column(name="CW_WH_NAME", length=64)
	private String cwWhName;

	@Basic
	@Column(name="CW_WH_NO", length=64)
	private String cwWhNo;

	@Basic
	@Column(name="CW_WH_OPERATE", length=64)
	private String cwWhOperate;

	@Basic
	@Column(name="CW_WH_PHOTO", length=256)
	private String cwWhPhoto;

	@Basic
	@Column(name="CW_WH_PLAN", length=256)
	private String cwWhPlan;

	@Basic
	@Column(name="CW_WH_STRUCTURE", length=64)
	private String cwWhStructure;

	@Basic
	@Column(name="CW_WH_TYPE", length=64)
	private String cwWhType;

	@Basic
	@Column(name="PM_CODE", length=64)
	private String pmCode;
}